[package]
name = "scrap-cli"
version = "0.1.0"
edition = "2024"
authors = ["Hyemi Baek <kimchi_mi@kakao.com>"]
license = "MIT"

[dependencies]
scrap = { path = "../scrap" }
uuid = { version = "1.0", features = ["v4"] }
clap = { version = "4.0", features = ["derive"] }